/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AccountCustomerManagedKeyObservation struct {

	// The ID of the Cognitive Account.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AccountCustomerManagedKeyParameters struct {

	// The ID of the Cognitive Account. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/upbound/provider-azure/apis/cognitiveservices/v1beta1.Account
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	CognitiveAccountID *string `json:"cognitiveAccountId,omitempty" tf:"cognitive_account_id,omitempty"`

	// Reference to a Account in cognitiveservices to populate cognitiveAccountId.
	// +kubebuilder:validation:Optional
	CognitiveAccountIDRef *v1.Reference `json:"cognitiveAccountIdRef,omitempty" tf:"-"`

	// Selector for a Account in cognitiveservices to populate cognitiveAccountId.
	// +kubebuilder:validation:Optional
	CognitiveAccountIDSelector *v1.Selector `json:"cognitiveAccountIdSelector,omitempty" tf:"-"`

	// The Client ID of the User Assigned Identity that has access to the key. This property only needs to be specified when there're multiple identities attached to the Cognitive Account.
	// +kubebuilder:validation:Optional
	IdentityClientID *string `json:"identityClientId,omitempty" tf:"identity_client_id,omitempty"`

	// The ID of the Key Vault Key which should be used to Encrypt the data in this Cognitive Account.
	// +crossplane:generate:reference:type=github.com/upbound/provider-azure/apis/keyvault/v1beta1.Key
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	KeyVaultKeyID *string `json:"keyVaultKeyId,omitempty" tf:"key_vault_key_id,omitempty"`

	// Reference to a Key in keyvault to populate keyVaultKeyId.
	// +kubebuilder:validation:Optional
	KeyVaultKeyIDRef *v1.Reference `json:"keyVaultKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in keyvault to populate keyVaultKeyId.
	// +kubebuilder:validation:Optional
	KeyVaultKeyIDSelector *v1.Selector `json:"keyVaultKeyIdSelector,omitempty" tf:"-"`
}

// AccountCustomerManagedKeySpec defines the desired state of AccountCustomerManagedKey
type AccountCustomerManagedKeySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccountCustomerManagedKeyParameters `json:"forProvider"`
}

// AccountCustomerManagedKeyStatus defines the observed state of AccountCustomerManagedKey.
type AccountCustomerManagedKeyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccountCustomerManagedKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// AccountCustomerManagedKey is the Schema for the AccountCustomerManagedKeys API. Manages a Customer Managed Key for a Cognitive Services Account.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azure}
type AccountCustomerManagedKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AccountCustomerManagedKeySpec   `json:"spec"`
	Status            AccountCustomerManagedKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountCustomerManagedKeyList contains a list of AccountCustomerManagedKeys
type AccountCustomerManagedKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountCustomerManagedKey `json:"items"`
}

// Repository type metadata.
var (
	AccountCustomerManagedKey_Kind             = "AccountCustomerManagedKey"
	AccountCustomerManagedKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountCustomerManagedKey_Kind}.String()
	AccountCustomerManagedKey_KindAPIVersion   = AccountCustomerManagedKey_Kind + "." + CRDGroupVersion.String()
	AccountCustomerManagedKey_GroupVersionKind = CRDGroupVersion.WithKind(AccountCustomerManagedKey_Kind)
)

func init() {
	SchemeBuilder.Register(&AccountCustomerManagedKey{}, &AccountCustomerManagedKeyList{})
}
