apiVersion: cognitiveservices.azure.upbound.io/v1beta1
kind: AccountCustomerManagedKey
metadata:
  annotations:
    meta.upbound.io/example-id: cognitiveservices/v1beta1/accountcustomermanagedkey
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cognitiveAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    identityClientId: ${azurerm_user_assigned_identity.example.client_id}
    keyVaultKeyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: cognitiveservices.azure.upbound.io/v1beta1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: cognitiveservices/v1beta1/accountcustomermanagedkey
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    customSubdomainName: example-account
    identity:
    - identityIds:
      - ${azurerm_user_assigned_identity.example.id}
      type: SystemAssigned, UserAssigned
    kind: Face
    location: West US
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: E0

---

apiVersion: keyvault.azure.upbound.io/v1beta1
kind: Vault
metadata:
  annotations:
    meta.upbound.io/example-id: cognitiveservices/v1beta1/accountcustomermanagedkey
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West US
    purgeProtectionEnabled: true
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: standard
    tenantId: ${data.azurerm_client_config.current.tenant_id}

---

apiVersion: keyvault.azure.upbound.io/v1beta1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: cognitiveservices/v1beta1/accountcustomermanagedkey
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    keyOpts:
    - decrypt
    - encrypt
    - sign
    - unwrapKey
    - verify
    - wrapKey
    keySize: 2048
    keyType: RSA
    keyVaultIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: cognitiveservices/v1beta1/accountcustomermanagedkey
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West US

---

